name: Generate metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Metrics embed
      uses: lowlighter/metrics@latest
      with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_traffic: yes
